url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/brezncup-munich" # the subpath of your site, e.g. /blog
title: "Brezncup Munich" # the name of your site, e.g. ACME Corp.
